GET http://localhost:3000/food HTTP/1.1

###

GET http://localhost:3000/food/1 HTTP/1.1

###

GET http://localhost:3000/food/g HTTP/1.1

###

POST http://localhost:3000/food HTTP/1.1
Content-Type: application/json

{
  "name": "Galletas",
  "calories": 20,
  "proteins": 1,
  "carbohydrates": 2,
  "fat": 3,
  "quantity": 1
}

###

PUT http://localhost:3000/food/3 HTTP/1.1
Content-Type: application/json

{
  "name": "Galleta",
  "calories": 40,
  "fat": 3.5
}

### 

DELETE http://localhost:3000/food/3 HTTP/1.1
